# Generated by Django 4.0.5 on 2022-06-24 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('largo', models.IntegerField(default='largo')),
                ('color', models.CharField(default='color', max_length=30)),
                ('precio', models.IntegerField(default='precio')),
            ],
            options={
                'verbose_name_plural': 'Collares',
            },
        ),
        migrations.CreateModel(
            name='Comida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=30)),
                ('tamaño', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=30)),
                ('peso', models.IntegerField(default='peso')),
                ('precio', models.IntegerField(default='precio')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('fecha', models.DateField()),
                ('duracion', models.DurationField()),
            ],
            options={
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.CharField(max_length=300)),
                ('fecha', models.DateField()),
                ('duracion', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='Pipeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=30)),
                ('peso', models.IntegerField(default='peso')),
                ('precio', models.IntegerField(default='precio')),
            ],
        ),
    ]
